### ISSUE TITLE
failed do initialize embedded Lanes

### ISSUE THREAD

**Issue by Necroso** [DizzasTeR/VCMP-Lua#10]
When starting the plugin with the latest update, this happens
[![image.png](https://i.postimg.cc/cC44WzfP/image.png)](https://postimg.cc/LYwMBNCV)

_**And also request for new functions too**: `player:setAlpha()`, `player.alpha`, `player.away`, `vehicle.immunity`_

**Comment by rasikhq** [comment]
Oh yes I forgot to mention that now we'll ship with lanes.lua, its a multi-threading library for lua, read more here: https://lualanes.github.io/lanes/

The lanes.lua must be placed in the server root directory, I will find a way to make it optional

Here's the script: https://github.com/LuaLanes/lanes/blob/master/src/lanes.lua
