### ISSUE TITLE
No such event named onPlayerModuleList exists / Thread nil value

### ISSUE THREAD

**Issue by Necroso** [DizzasTeR/VCMP-Lua#13]
```lua
Event.bind("onPlayerModuleList", onPlayerModuleList)
```
![](https://imgur.com/d3nVCsV.png)

Same example provided on the wiki
![](https://imgur.com/rfi42WI.png)

**Comment by rasikhq** [comment]
Thread is only available in experimental mode (along with some other features) because any experimental feature can cause a server crash due to the nature of the feature. I'd suggest using lanes for your multi-threading tasks.

I'll look into the event not found issue soon
