### ISSUE TITLE
Request Server functions

### ISSUE THREAD

**Issue by Necroso** [DizzasTeR/VCMP-Lua#14]
Squirrel
```squirrel
SetMaxPlayers(int)
SetMaxHeight(int)
```

Lua Suggestion
```lua
Server.maxPlayers = int
Server.maxHeight = int
```

**Comment by rasikhq** [comment]
Max players functions were added. Max height is actually Server.flightAltitude which is renamed to MaxHeight in official.

Check release notes for info about max player functions
