### ISSUE TITLE
onPlayerDisconnect: Inconsistency between Player 0 and Player 1

### ISSUE THREAD

**Issue by Necroso** [DizzasTeR/VCMP-Lua#16]
When there is more than one player, players 0 and 1 get confused by being indexed in the onPlayerDisconnect event.

If Player 0 leaves the server, it ends up being recognized as ID 1

**Console logs:**
Players connecting
```
Player 'Player0' ID 0 connected.
Player 'Player1' ID 1 connected.
Player 'Player2' ID 2 connected.
```

Player 0 leaving (_The console shows that it is player 0 leaving, but the event recognizes it as player 1_)
```
Disconnecting player 'Player0' at ID 0, sent quit packet with reason 1.
Player 'Player0' ID 0 disconnected.
Player1 left with the ID 1
```

Script in onPlayerDisconnect:
```lua
print(player.name .. " left with the ID " .. player.id)
```

**Comment by rasikhq** [comment]
Looking at the source I'm surprised the server didn't crash over this, but I'll investigate this when I can. I do think I know what's causing it.
