### ISSUE TITLE
Lua machine not exported

### ISSUE THREAD

**Issue by habi498** [DizzasTeR/VCMP-Lua#5]
Hello, few days ago i noticed this in java plugin and decided to take a look at this plugin too.

In squirrel, stormeus does something like SendPluginCommand(0x7DC..., "");
Also on VcmpPluginInit, you can see somethings are 'exported'- the virtual machine.
Why this is needed is that if someone decided to write a plugin for this lua language, they need access to the lua virtual machine.

**Comment by rasikhq** [comment]
I guess I forgot about it, can definitely add it whenever the need arises, if you require it for some work I can try to get it done sooner otherwise I'll wait until someone really needs it because its not something that is used very often

**Comment by rasikhq** [comment]
Closing for now, will re-open and implement if someone actually needs this for some use case
