### ISSUE TITLE
Map.hideObject does not support correct coordinate data

### ISSUE THREAD

**Issue by Necroso** [DizzasTeR/VCMP-Lua#6]
I'm trying to hide the following object
```lua
Map.hideObject(474, -393.412, -505.822, 9.92519)
```
This returns the following error:
`
[error] Event callback error: stack index 2, expected number, received number: not a numeric type that fits exactly an integer (number maybe has significant decimals) (bad argument into 'void(int, short, short, short)')
`

The game only hides an object if it uses a decimal value, otherwise the object is not hidden.

**Comment by rasikhq** [comment]
Fixed in alpha release 2.4.X
